### PR TITLE
Convert from FT to SPM

### PR DESCRIPTION
**Pull request by neurofractal**
Hi Tim, 

This is a script to convert from Fieldtrip data structure to SPM, while performing the coreg and forward modelling in SPM.

Unsure if this is the right place for it? Let me know if you have any more thoughts. 

Cheers, 

R

### CODE REVIEW

**Comment by tierneytim** [comment]
can you add minimal testData and test code to testOPM_create so that cahnges can be verified on different machines before merging?

**Comment by neurofractal** [comment]
OK @tierneytim should be good

**Comment by georgeoneill** [comment]
Hi @neurofractal, given we didnt merge this before the subsequent changes I shall close this pull _for now_, but once you are happy with the nature of your code after I've update the repo this afternoon, please send the request again and then bother me untill I approve!

**Comment by neurofractal** [comment]
OK no problem.

**Pull request closed without merging**
